/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ioixd_blackbox_Native */

#ifndef _Included_net_ioixd_blackbox_Native
#define _Included_net_ioixd_blackbox_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    loadPlugin
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ioixd_blackbox_Native_loadPlugin
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    enablePlugin
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_net_ioixd_blackbox_Native_enablePlugin
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    disablePlugin
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_net_ioixd_blackbox_Native_disablePlugin
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    libraryNames
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ioixd_blackbox_Native_libraryNames
  (JNIEnv *, jclass);

/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    libraryHasFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_net_ioixd_blackbox_Native_libraryHasFunction
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    sendEvent
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_net_ioixd_blackbox_Native_sendEvent
  (JNIEnv *, jclass, jstring, jstring, jobject, jboolean);

/*
 * Class:     net_ioixd_blackbox_Native
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILorg/bukkit/plugin/Plugin;[Ljava/lang/Object;Z)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_net_ioixd_blackbox_Native_execute
  (JNIEnv *, jclass, jstring, jstring, jint, jobject, jobjectArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
