/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ioixd_blackbox_BiConsumerLink */

#ifndef _Included_net_ioixd_blackbox_BiConsumerLink
#define _Included_net_ioixd_blackbox_BiConsumerLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ioixd_blackbox_BiConsumerLink
 * Method:    acceptNative
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_net_ioixd_blackbox_BiConsumerLink_acceptNative
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
